name: Deploy to EC2

on:
  push:
    branches:
      - main _backup # This will trigger the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -p 22 -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Debug Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Checking directory contents..."
            cd /home/ubuntu/abacux_data_visual/abacux_charts || exit
            ls -la

            echo "Checking Docker containers..."
            docker ps

            echo "Checking if port 80 is in use..."
             lsof -i :80 || true

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This ensures the deploy job runs after build

    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -p 22 -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy and Restart Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/abacux_data_visual/abacux_charts || exit
            git fetch
            git pull origin main || echo "Git pull failed"
            docker-compose -f docker-compose.yml down
            docker-compose -f docker-compose.yml up --build -d
